import numpy as np

# Random state
RANDOM_SEED = 42
RANDOM_STATE = np.random.default_rng(seed=RANDOM_SEED)

# Movement scale
STEP_SIZE = 2

# Gaussian Mixture
N_GMM_COMPONENTS = 10
EPSILON = 1e-6
RELEVANCE_RADIUS = 10

# NRPA
LEARNING_RATE = 1e-2

# GNRPA and ABGNRPA parameters
GAMMA = 0.1
TAU = 10
N_SAMPLES_TO_CHOOSE_FROM = 20

# Gaussian convolution
STATE_DISTANCE_PARAMETER = 50
ACTION_DISTANCE_PARAMETER = 50

# MCTS, RAVE and GRAVE
N_DISCRETE_ACTIONS = 20
EXPLORATION_CONSTANT = np.sqrt(2)
DISCRETE_ACTIONS = np.arange(0, 1, 1 / N_DISCRETE_ACTIONS)

# cMCTS and cRAVE/ cGRAVE parameters
PROGRESSIVE_WIDENING_PARAMETER = 0.5
BIAS_VALUE = 1e-6
N_VISITS_REFERENCE = 50
