import numpy as np

# Random state
RANDOM_SEED = 42
RANDOM_STATE = np.random.default_rng(seed=RANDOM_SEED)

# Movement scale
STEP_SIZE = 2

# Gaussian Mixture
N_GMM_COMPONENTS = 10
EPSILON = 1e-6
RELEVANCE_RADIUS = 10

# NRPA
LEARNING_RATE = 1e-3

# GNRPA and ABGNRPA parameters
GAMMA = 1e-4
TAU = 10
N_SAMPLES_TO_CHOOSE_FROM = 20

# Gaussian convolution
STATE_DISTANCE_PARAMETER = 10
ACTION_DISTANCE_PARAMETER = 10

# MCTS and cRAVE/ cGRAVE parameters
EXPLORATION_CONSTANT = np.sqrt(2)
PROGRESSIVE_WIDENING_PARAMETER = 2
BIAS_VALUE = 2
N_VISITS_REFERENCE = 50
